<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260509200613 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE allergene (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE avis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note INT NOT NULL, commentaire TEXT DEFAULT NULL, valide BOOLEAN NOT NULL, date_avis TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8F91ABF0FB88E14F ON avis (utilisateur_id)');
        $this->addSql('CREATE TABLE commande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_commande VARCHAR(50) NOT NULL, date_commande TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_prestation DATE NOT NULL, heure_livraison TIME(0) WITHOUT TIME ZONE NOT NULL, adresse_livraison VARCHAR(255) NOT NULL, ville_livraison VARCHAR(100) NOT NULL, nb_personnes INT NOT NULL, prix_menu NUMERIC(10, 2) NOT NULL, prix_livraison NUMERIC(10, 2) NOT NULL, prix_total NUMERIC(10, 2) NOT NULL, statut VARCHAR(50) NOT NULL, pret_materiel BOOLEAN NOT NULL, materiel_restitue BOOLEAN NOT NULL, utilisateur_id INT NOT NULL, menu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6EEAA67DFB88E14F ON commande (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_6EEAA67DCCD7E912 ON commande (menu_id)');
        $this->addSql('CREATE TABLE contact (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(150) NOT NULL, description TEXT NOT NULL, email VARCHAR(180) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE historique_statut (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statut VARCHAR(50) NOT NULL, date_heure TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, commentaire TEXT DEFAULT NULL, mode_contact VARCHAR(50) DEFAULT NULL, commande_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2C2650E382EA2E54 ON historique_statut (commande_id)');
        $this->addSql('CREATE TABLE horaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, jour VARCHAR(15) NOT NULL, heure_ouverture TIME(0) WITHOUT TIME ZONE NOT NULL, heure_fermeture TIME(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE image_menu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url VARCHAR(255) NOT NULL, menu_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8F3FD00DCCD7E912 ON image_menu (menu_id)');
        $this->addSql('CREATE TABLE menu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(100) NOT NULL, description TEXT DEFAULT NULL, theme VARCHAR(50) DEFAULT NULL, regime VARCHAR(50) DEFAULT NULL, nb_personnes_min INT NOT NULL, prix NUMERIC(10, 2) NOT NULL, stock INT NOT NULL, conditions TEXT DEFAULT NULL, actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE menu_plat (menu_id INT NOT NULL, plat_id INT NOT NULL, PRIMARY KEY (menu_id, plat_id))');
        $this->addSql('CREATE INDEX IDX_E8775249CCD7E912 ON menu_plat (menu_id)');
        $this->addSql('CREATE INDEX IDX_E8775249D73DB560 ON menu_plat (plat_id)');
        $this->addSql('CREATE TABLE newsletter (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, date_inscription TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE plat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, type VARCHAR(50) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE plat_allergene (plat_id INT NOT NULL, allergene_id INT NOT NULL, PRIMARY KEY (plat_id, allergene_id))');
        $this->addSql('CREATE INDEX IDX_6FA44BBFD73DB560 ON plat_allergene (plat_id)');
        $this->addSql('CREATE INDEX IDX_6FA44BBF4646AB2 ON plat_allergene (allergene_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE avis ADD CONSTRAINT FK_8F91ABF0FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67DCCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE historique_statut ADD CONSTRAINT FK_2C2650E382EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE image_menu ADD CONSTRAINT FK_8F3FD00DCCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_plat ADD CONSTRAINT FK_E8775249CCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE menu_plat ADD CONSTRAINT FK_E8775249D73DB560 FOREIGN KEY (plat_id) REFERENCES plat (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE plat_allergene ADD CONSTRAINT FK_6FA44BBFD73DB560 FOREIGN KEY (plat_id) REFERENCES plat (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE plat_allergene ADD CONSTRAINT FK_6FA44BBF4646AB2 FOREIGN KEY (allergene_id) REFERENCES allergene (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE avis DROP CONSTRAINT FK_8F91ABF0FB88E14F');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67DFB88E14F');
        $this->addSql('ALTER TABLE commande DROP CONSTRAINT FK_6EEAA67DCCD7E912');
        $this->addSql('ALTER TABLE historique_statut DROP CONSTRAINT FK_2C2650E382EA2E54');
        $this->addSql('ALTER TABLE image_menu DROP CONSTRAINT FK_8F3FD00DCCD7E912');
        $this->addSql('ALTER TABLE menu_plat DROP CONSTRAINT FK_E8775249CCD7E912');
        $this->addSql('ALTER TABLE menu_plat DROP CONSTRAINT FK_E8775249D73DB560');
        $this->addSql('ALTER TABLE plat_allergene DROP CONSTRAINT FK_6FA44BBFD73DB560');
        $this->addSql('ALTER TABLE plat_allergene DROP CONSTRAINT FK_6FA44BBF4646AB2');
        $this->addSql('DROP TABLE allergene');
        $this->addSql('DROP TABLE avis');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE historique_statut');
        $this->addSql('DROP TABLE horaire');
        $this->addSql('DROP TABLE image_menu');
        $this->addSql('DROP TABLE menu');
        $this->addSql('DROP TABLE menu_plat');
        $this->addSql('DROP TABLE newsletter');
        $this->addSql('DROP TABLE plat');
        $this->addSql('DROP TABLE plat_allergene');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
